# Generated by Django 3.2 on 2022-11-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_choice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
    ]
