# Generated by Django 3.2 on 2022-11-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='student_id',
            new_name='user',
        ),
    ]
